### ISSUE TITLE
Should verify downloads

### ISSUE THREAD

**Issue by ecki** [nccgroup/Wubes#1]
Thanks a lot for this project. It already works great. In the spirit of a trustworthy hardened operating system it should however contain an option to download and verify a fixed version of Firefox, Python and NPP with a pre-delivered hash.

**Comment by saidelike** [comment]
Thanks. Glad you are enjoying this project. I have a few problems with your proposal:

- I'd rather have the latest version of Firefox than a predefined version of it. So we would need a way to dynamically fetch the right hash, which then is hard as we can't trust what we remotely fetch (at least we have the same amount of trust as not checking it in the first place). 
- if we get fake installers that are malicious and runs into our sandbox, we are still protected due to the sandbox layer, which would not be the case if we downloaded them from our host for instance.

Note: We could do it for Python/NPP though as atm we use a hardcoded version

**Comment by ecki** [comment]
Yeah, it’s probably not worth maintaining regular hash updates for the specific usecase.
